const ERR_TASK_MANAGER_INVALID_TITLE = "ERR_TASK_MANAGER_INVALID_TITLE";
const ERR_TASK_MANAGER_INVALID_DESCRIPTION =
  "ERR_TASK_MANAGER_INVALID_DESCRIPTION";
const ERR_TASK_MANAGER_INVALID_IS_COMPLETION =
  "ERR_TASK_MANAGER_INVALID_IS_COMPLETION";
const ERR_TASK_MANAGER_DEFAULT = "ERR_TASK_MANAGER_DEFAULT";

module.exports = {
  ERR_TASK_MANAGER_INVALID_TITLE,
  ERR_TASK_MANAGER_INVALID_DESCRIPTION,
  ERR_TASK_MANAGER_INVALID_IS_COMPLETION,
  ERR_TASK_MANAGER_DEFAULT,
};
