const ERR_TASK_MANAGER_INVALID_TITLE = 'ERR_TASK_MANAGER_INVALID_TITLE';
const ERR_TASK_MANAGER_INVALID_DESCRIPTION =
  'ERR_TASK_MANAGER_INVALID_DESCRIPTION';
const ERR_TASK_MANAGER_INVALID_IS_COMPLETION =
  'ERR_TASK_MANAGER_INVALID_IS_COMPLETION';
const ERR_TASK_MANAGER_DEFAULT = 'ERR_TASK_MANAGER_DEFAULT';
const ERR_TASK_MANAGER_INVALID_TASK_ID = 'ERR_TASK_MANAGER_INVALID_TASK_ID';
const ERR_TASK_MANAGER_TASK_NOT_FOUND = 'ERR_TASK_MANAGER_TASK_NOT_FOUND';
const ERR_TASK_MANAGER_INVALID_PRIORITY = 'ERR_TASK_MANAGER_INVALID_PRIORITY';

module.exports = {
  ERR_TASK_MANAGER_INVALID_TITLE,
  ERR_TASK_MANAGER_INVALID_DESCRIPTION,
  ERR_TASK_MANAGER_INVALID_IS_COMPLETION,
  ERR_TASK_MANAGER_DEFAULT,
  ERR_TASK_MANAGER_INVALID_TASK_ID,
  ERR_TASK_MANAGER_TASK_NOT_FOUND,
  ERR_TASK_MANAGER_INVALID_PRIORITY,
};
